### ISSUE TITLE
Adding a HealthBar 

### ISSUE THREAD

**Issue by SykoDaedalus** [lla-dane/Jack-in-the-wild#2]
The player does not have a healthbar which makes it difficult to judge the player's current health. A healthbar should be added so that players can know about their current health.

**Comment by darshi1337** [comment]
@phantomgithub 
Thanks for the issue. If you want you can contribute this feature itself. Also tag me or @kmtGryffindor20 to get a quick response.

**Comment by darshi1337** [comment]
#3 it is then let me see
